purge Azure CDN endpoint from deploy stage (#51)
* purge Azure CDN endpoint from deploy stage

  - add new variables to the pipeline
  - purge home, index, 404 and version
  - validate live vs release website versions (purge)

solved: #47

* revert to version.txt instead of html

diff --git a/src/ClientApp/azure-pipelines.yml b/src/ClientApp/azure-pipelines.yml
--- a/src/ClientApp/azure-pipelines.yml
+++ b/src/ClientApp/azure-pipelines.yml
@@ -60,21 +60,30 @@ stages:
         deploy:
           steps:
           - script: |
-              echo '##vso[task.setvariable variable=nextVersion]'$(cat "$(Pipeline.Workspace)/drop/version.txt")
-            displayName: 'set nextVersion variable'
-            name: setVarNextVersion
+              echo '##vso[task.setvariable variable=releaseVersion]'$(cat "$(Pipeline.Workspace)/drop/version.txt")
+            displayName: 'set release version'
+            name: setVarReleaseVersion
 
-          - script: |
-              az login --service-principal -u $(azureArmClientId) -p $(azureArmClientSecret) --tenant $(azureArmTenantId)
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination \$web --account-name $(azureStorageAccountName)
-              echo "content uploaded at https://$(azureStorageAccountName).azureedge.net/index.html"
-            displayName: 'upload to Azure Storage static website hosting'
-                    
-          - task: GithubRelease@0 
-            displayName: 'Create GitHub Release'      
+          - task: GithubRelease@0
+            displayName: 'create or edit GitHub release'
             inputs:
               gitHubConnection: $(gitHubServiceConnectionName)
               tagSource: manual
-              tag: $(nextVersion)
-              assets: $(Pipeline.Workspace)/drop
-              title: 'Fabrikam Drone Status App $(nextVersion)'
+              action: edit
+              tag: $(releaseVersion)
+              title: 'Fabrikam Drone Status App $(releaseVersion)'
+          
+          - script: |
+              az login --service-principal -u $(azureArmClientId) -p $(azureArmClientSecret) --tenant $(azureArmTenantId)
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination \$web --account-name $(azureStorageAccountName)
+              az cdn endpoint purge --resource-group $(azureResourceGroup) --profile-name $(azureCdnName) --name $(azureCdnName) --content-paths '/' '/index.html' '/404.html' '/version.txt'
+              AZURE_CDN_ENDPOINT_HOSTNAME=$(az cdn endpoint show --resource-group $(azureResourceGroup) --name $(azureCdnName) --profile-name $(azureCdnName) --query hostName -o tsv)
+              echo "Azure CDN endpooint host ${AZURE_CDN_ENDPOINT_HOSTNAME}"
+              echo '##vso[task.setvariable variable=azureCndEndpointHost]'$AZURE_CDN_ENDPOINT_HOSTNAME
+            displayName: 'upload to Azure Storage static website hosting and purge Azure CDN endpoint'
+          
+          - script: |
+              liveVersion=$(curl --fail --silent "https://$(azureCndEndpointHost)/version.txt")
+              [[ $liveVersion == $(releaseVersion) ]] && echo -e "\033[1;32m## [Passed] website validation Ok: $liveVersion is live now\033[0m" || >&2 echo -e "\033[0;31m## [Fail] website validation Fail: expected $(releaseVersion) - actual $liveVersion\033[0m"
+            displayName: 'validate website version'
+            failOnStderr: true
